export const carouselMedia = [
  { type: 'image', src: '/carrousel1.jpg' },
  { type: 'image', src: '/carrousel2.jpg' },
  { type: 'image', src: '/carrousel3.jpg' },
  { type: 'image', src: '/carrousel4.jpg' },
  { type: 'image', src: '/carrousel5.jpg' },
  { type: 'image', src: '/BACHILLERAO INTERNACIONAL.jpg' },
  { type: 'image', src: '/DIRECTORIO ACADEMICO.jpg' },
  { type: 'image', src: '/EN EL GLP DESARROLLAMOS TU POTENCIAL.jpg' },
  { type: 'image', src: '/enfasis ciencias aplicadas (2).jpg' },
  { type: 'image', src: '/ENFASIS EN DEPORTES.jpg' },
  { type: 'image', src: '/ENFASIS EN MUSICA Y ARTES.jpg' },
  { type: 'image', src: '/ENFASIS HUMANIDADES.jpg' },
  { type: 'image', src: '/PERFIL DEL ESTUDIANTE.jpg' },
  { type: 'image', src: '/PROCESO DE ADMISION.jpg' },
  { type: 'image', src: '/PROYECTO EDUCATIVO.jpg' },
  { type: 'image', src: '/PSICOLOGIA.jpg' },
  { type: 'image', src: '/SOBRE NOSOTROS.jpg' },
  { type: 'image', src: '/uniformes.jpeg' },
  { type: 'image', src: '/enfasis ciencias aplicadas.jpg' },
  {
    type: 'video',
    videoId: 'z2bfydWT08g',
  },
  {
    type: 'video',
    videoId: 'ZuLdyHzYg0w',
  },
];
