export const carouselMedia = [
  { type: 'image', src: '/carrousel1.jpg' },
  { type: 'image', src: '/carrousel2.jpg' },
  { type: 'image', src: '/carrousel3.jpg' },
  { type: 'image', src: '/carrousel4.jpg' },
  { type: 'image', src: '/carrousel5.jpg' },
  { type: 'image', src: '/BACHILLERAO INTERNACIONAL.jpg' },
  { type: 'image', src: '/DIRECTORIO ACADEMICO.jpg' },
  { type: 'image', src: '/EN EL GLP DESARROLLAMOS TU POTENCIAL.jpg' },
  { type: 'image', src: '/enfasis ciencias aplicadas (2).jpg' },
  { type: 'image', src: '/ENFASIS EN DEPORTES.jpg' },
  { type: 'image', src: '/ENFASIS EN MUSICA Y ARTES.jpg' },
  { type: 'image', src: '/ENFASIS HUMANIDADES.jpg' },
  { type: 'image', src: '/PERFIL DEL ESTUDIANTE.jpg' },
  { type: 'image', src: '/PROCESO DE ADMISION.jpg' },
  { type: 'image', src: '/PROYECTO EDUCATIVO.jpg' },
  { type: 'image', src: '/PSICOLOGIA.jpg' },
  { type: 'image', src: '/SOBRE NOSOTROS.jpg' },
  { type: 'image', src: '/uniformes.jpeg' },
  { type: 'image', src: '/enfasis ciencias aplicadas.jpg' },
  {
    type: 'video',
    src: 'https://corgimpin-my.sharepoint.com/personal/comercial_gimnasiolospinos_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcomercial%5Fgimnasiolospinos%5Fedu%5Fco%2FDocuments%2FDatos%20adjuntos%2F1920x1080%5F2%20%281%29%2Emp4&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ea387b95c%2D5674%2D425d%2Dad35%2D949cc636a132',
  },
  {
    type: 'video',
    src: 'https://corgimpin-my.sharepoint.com/personal/comercial_gimnasiolospinos_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcomercial%5Fgimnasiolospinos%5Fedu%5Fco%2FDocuments%2FDatos%20adjuntos%2FGLP%5F25%5FENE%5FREDES%5FBIENVENIDA%5F1920X1080%2Emp4&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Eb624ca0b%2D7424%2D4c00%2Dac2f%2Dd2b982c19931',
  },
];
